 #!/bin/bash
export CLASSPATH="../lib/antlr-4.7.2-complete.jar:$CLASSPATH"
# java -Xmx500M -cp "../lib/antlr-4.7.2-complete.jar:$CLASSPATH" org.antlr.v4.Tool ../gen/LittleGrammar.g4
java -jar ../lib/antlr-4.7.2-complete.jar -o ../gen LittleGrammar.g4
javac -d ../gen/ Builder.java ../gen/LittleGrammar*.java

cd ../gen/

java Builder ../inputs/fibonacci.micro fibonacci
java Builder ../inputs/loop.micro loop
java Builder ../inputs/nested.micro nested
java Builder ../inputs/sqrt.micro sqrt

